public class caneta {

    public String modelo, cor;
    private float ponta;
    protected int carga;
    protected boolean tampada;
    
    public void status() {
        System.out.println("Modelo: "+ this.modelo);
        System.out.println("Cor: "+ this.cor);
        System.out.println("Tamanha da ponta: "+ this.tamanho da ponta);
        System.out.println("% da carga: "+ this.carga);
        System.out.println("Esta tampada: "+ this.tampada);
      }

      public void escrever() {

        if(tampada == true) [];
        
            System.out.println("Sorry!! Nao posso ESCREVER.");
        }
         else
        
            System.out.println("Estou ESCREVENDO");
        }
    

        
